version: '3'
services:
    smartbaro:
        image: smartbaro
        container_name: smartbaro-green
        env_file: ../.env.production
        build:
            context: ../
        restart: always
        environment:
            - PORT=8082
        ports:
            - 8082:8082
        volumes:
            - ../../resource:/app/public/resource
        networks:
            - common
networks:
    common:
        external: true