version: "3"
services:
    database:
        restart: always
        image: database
        container_name: database
        build: ./database
        ports:
            - '3306:3306'
        volumes:
            - ./data/mysql:/var/lib/mysql
        env_file: .env
        environment:
            - TZ=Asia/Seoul
        networks:
            - common

    backend:
        image: backend
        container_name: backend
        build: ./smartbaro-backend
        restart: always
        volumes:
            - ./data/:/usr/src/app/data/
            - ./resource/:/usr/src/app/resource/
            - ./smartbaro-backend:/usr/src/app
        ports:
            - "5000:5000"
        env_file: .env
        environment:
            - PROFILE=development
            - HOST=http://localhost:5000
            - MYSQL_HOST=database
        networks:
            - common
            
    smartbaro:
        container_name: smartbaro
        build:
            context: ./smartbaro
            target: dev
        restart: always
        command: yarn dev
        volumes:
            - ./smartbaro:/app
            - ./resource/:/app/public/resource
            - /app/node_modules
            - /app/.next
        ports:
            - 8080:8080
        environment:
            - PORT=8080
            - NODE_ENV=development
            - NEXT_PUBLIC_HOST=http://localhost:8080
            - NEXT_PUBLIC_BACKEND=http://backend:5000
        networks:
            - common

    smartbaro-admin:
        image: smartbaro-admin
        container_name: smartbaro-admin
        build:
            context: ./smartbaro-admin
            target: dev
        restart: always
        command: yarn dev
        volumes:
            - ./smartbaro-admin:/app
            - ./resource/:/app/public/resource
            - /app/node_modules
            - /app/.next
        ports:
            - '7070:7070'
        environment:
            - PORT=7070
            - NODE_ENV=development
            - NEXT_PUBLIC_HOST=http://localhost:7070
            - NEXT_PUBLIC_BACKEND=http://backend:5000
            - NEXT_PUBLIC_API=http://localhost:5000
            - NEXT_PUBLIC_TOKENNAME=SMARTBARO-ADMIN
        networks:
            - common

networks:
    common:
        driver: bridge