version: '3'
services:
    backend:
        image: backend
        build: ./
        restart: always
        container_name: backend
        volumes:
            - ./:/usr/src/app
            - ../data/:/usr/src/app/data/
            - ../resource/:/usr/src/app/resource/
        ports:
            - '5000:5000'
        env_file: ../.env
        environment:
            - PROFILE=production
            - HOST=http://
            - HOST_IP=
        networks:
            - common
networks:
    common:
        external: true
